### ISSUE TITLE
inner members not recognized for "standard" multipolygons

### ISSUE THREAD

**Issue by tyrasd** [plepe/pgmapcss#103]
Compare the output of the following MapCSS http://pgmapcss.openstreetbrowser.org/?style=1d494&zoom=16&lat=46.3613&lon=11.1898 with the [desired shape](http://overpass-turbo.eu/?w=type:relation%20and%20id:2873990%20global&R). Inner members of *standard* multipolygons appear to be ignored?!

**Comment by plepe** [comment]
Thanks for pointing me to this. The problem was, that members which are non-closed ways are merged together, but not converted to polygons -> then substracting inner members will not change the geometry. Strange, that I missed those polygons.
