### ISSUE TITLE
Dates in CHANGELOG.md

### ISSUE THREAD

**Issue by Skippern** [plepe/pgmapcss#111]
Dates in CHANGELOG.md for release of version 0.10.0 and 0.10.1 seems to be wrong, or was they really released over a year ago?

**Comment by plepe** [comment]
Oh, you are right! Thanks for pointing it out ...

**Comment by Skippern** [comment]
And you are still one year behind in the CHANGELOG

**Comment by plepe** [comment]
Ouch, how embarrassing. I'm currently too distracted :-) Just fixed it.

Thanks for reminding!
